############# French navigation ##############

# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "Services"
url = "/Services"
weight = 2

[[main]]
weight = 3
name = "Réalisations"

[[main]]
parent = "Réalisations"
name = "Interieur"
url = "/Réalisations"

[[main]]
parent = "Réalisations"
name = "Architectural"
url = "/Réalisations"

[[main]]
parent = "Réalisations"
name = "Equipements Sportifs & Culturels"
url = "/Réalisations"

[[main]]
weight = 4
name = "A propos de nous"

[[main]]
parent = "A propos de nous"
name = "Histoire"
url = "/about"

[[main]]
parent = "A propos de nous"
name = "Durabilité"
url = "/blog"

[[main]]
parent = "A propos de nous"
name = "Contacts"
url = "/contact"


# footer menu
[[footer]]
name = "Nous contacter"
url = "/about"
weight = 1

[[footer]]
name = "Mentions légales"
url = "/privacy-policy"
weight = 3

[[footer]]
name = "Cookies"
url = "/privacy-policy"
weight = 4