############# English navigation ##############

# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "Services"
url = "/about"
weight = 2

[[main]]
name = "Réalisations"
url = "/elements"
weight = 3

[[main]]
weight = 4
name = "A propos de nous"

[[main]]
parent = "A propos de nous"
name = "Histoire"
url = "/blog"

[[main]]
parent = "A propos de nous"
name = "Durabilité"
url = "/contact"

[[main]]
parent = "A propos de nous"
name = "Contacts"
url = "/authors"

[[main]]
parent = "Pages"
name = "Categories"
url = "/categories"

[[main]]
parent = "Pages"
name = "404 Page"
url = "/404"


# footer menu
[[footer]]
name = "Contact"
url = "/about"
weight = 1

[[footer]]
name = "Mentions légales"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3

[[footer]]
name = "Cookie Policy"
url = "/privacy-policy"
weight = 4
